name: Update Love Count

on:
  repository_dispatch:
    types: [love_added]

jobs:
  update-love:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update love count
        run: |
          IMAGE_NAME=$(jq -r '.client_payload.image' $GITHUB_EVENT_PATH)
          echo "Image to update: $IMAGE_NAME"

          COUNT=$(jq --arg img "$IMAGE_NAME" '
            if has($img) then .[$img] += 1 else .[$img] = 1 end
          ' loves.json)

          echo "$COUNT" > loves.json

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add loves.json
          git commit -m "❤️ +1 for $IMAGE_NAME"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
